services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://app:${POSTGRES_PASSWORD:-password}@database/app?schema=public

    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17-alpine
    ports:
      - 30011:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app -U app"]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    # Augmenter les ressources allouées à PostgreSQL
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

volumes:
  database_data:
